ModelsForms/ModelsForms/urls.py
from django.contrib import admin
from django.urls import path,include
from MyApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('myapp/',include('MyApp.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special')
]

ModelsForms/MyApp/urls.py
from django.urls import path
from MyApp import views

app_name='MyApp'

urlpatterns=[
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login')
    
]

ModelsForms/MyApp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

ModelsForms/MyApp/forms.py
from django import forms
from django.contrib.auth.models import User
from MyApp.models import UserProfileInfo

class UserInfoForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('profile_pic','portfolio_site')

ModelsForms/MyApp/views.py
from django.shortcuts import render
from MyApp.forms import UserInfoForm,UserProfileInfoForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    return render(request,'index.html')

@login_required
def special(request):
    return HttpResponse("YOU ARE LOGGED IN")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered=False
    if request.method=="POST":
        user_form=UserInfoForm(request.POST)
        user_profile_form=UserProfileInfoForm(request.POST)

        if user_form.is_valid() and user_profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile=user_profile_form.save(commit=False)
            profile.user=user

            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']

            profile.save()

            registered=True
        else:

            print(user_form.errors,user_profile_form.errors)
    else:
        user_form=UserInfoForm()
        user_profile_form=UserProfileInfoForm()

    return render(request,'register.html',
    {'user_form':user_form,
    'user_profile_form':user_profile_form,
    'registered':registered
    })

def user_login(request):

    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=username,password=password)

        if user:
            if user.is_activate:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('YOUR ACCOUNT IS NOT ACTIVATE')

        else:
            print('SOMEONE TRIED TO LOGIN AND FAILED')
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        return render(request,'login.html',{})

ModelsForms/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="navbar-nav">
          {# Django Home Link / Admin Link / Register Link#}
          <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
          <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
          <a class="nav-item nav-link" href="{% url 'MyApp:register' %}">Register</a>
          {% if user.is_authenticated %}
          <a href="{% url 'logout'%}" class="nav-item nav-link">Logout</a>
          {%else%}
          <a href="{%url 'MyApp:user_login'%}" class="nav-item nav-link">Login</a>
          {%endif%}
          
        </div>
      </nav>
      <div class="container">
          {% block body_block %}
          
         {% endblock %}
      </div>
</body>
</html>

ModelsForms/templates/index.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container">
    <div class="jumbotron">
        <h1>THIS IS INDEX PAGE</h1>
    </div>
    
</div>
{% endblock %}

ModelsForms/templates/login.html
{%extends 'base.html'%}
{%block body_block%}
<div class="container">
    <div class="jumbotron">
        <h1>Please log in</h1>
    <form action="{%url 'MyApp:user_login'%}" method="post">
        {%csrf_token%}
        <label for="username">Username</label>
        <input type="text" name="username" placeholder="Enter Username">
        <label for="password">Password</label>
        <input type="password" name="password" placeholder="Enter Password">

        <input type="submit" value="Login">
    </form>
    </div>
    
</div>
{%endblock%}

ModelsForms/templates/register.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container">
    <div class="jumbotron">
        <h1>THIS IS REGISTERATION PAGE</h1>
        {% if registered %}
             <h1>Thanks for filling out form</h1>
        {%else%}
             <h1>Register Here</h1>
             <h1>Fill out the form</h1>
             <form enctype="multipart/form-data" method="post">
                {% csrf_token %}
                {{user_form.as_p}}
                {{user_profile_form.as_p}}
                <input type="submit" value="Register" >
             </form>
             
        {%endif%}
    </div>
</div>
{% endblock %}